### ISSUE TITLE
Detailed grade

### ISSUE THREAD

**Issue by madclam** [codalab/chagrade#115]
When an instructor gives a grade based on several sub-criteria, the student only gets the overall grade (sum of sub-criteria) as feed-back. He should be able to see the details.

**Comment by brendon-lind** [comment]
<img width="1032" alt="Screen Shot 2020-04-20 at 3 52 00 PM" src="https://user-images.githubusercontent.com/56202662/79807189-0dfb0180-831f-11ea-9959-930e562fb536.png">

**Comment by brendon-lind** [comment]
<img width="841" alt="Screen Shot 2020-04-20 at 4 04 07 PM" src="https://user-images.githubusercontent.com/56202662/79807746-b067b480-8320-11ea-85e2-ccf2eceb867e.png">
