### ISSUE TITLE
Questions in reverse order

### ISSUE THREAD

**Issue by madclam** [codalab/chagrade#120]
Questions appear to students in the reverse order provided in the form created by the instructors.

**Comment by madclam** [comment]
Also the questions do no appear as numbered to students.

**Comment by brendon-lind** [comment]
We are unable to reproduce at current time.

**Comment by gibsonbailey** [comment]
> We are unable to reproduce at current time.

I believe there is some randomness that we are getting rid of with this change. It may not be consistently reproducible, but this change should help!
