### ISSUE TITLE
Staging Server + Testing Instructions

### ISSUE THREAD

**Issue by Tthomas63** [codalab/chagrade#16]
The staging server for Chagrade is currently located at: http://134.158.74.61/
This server also uses a Chahub Staging Server for Auth at: https://chahub-staging.herokuapp.com/

# Testing:

### Auth:
- First be sure you have an account on the Chahub server at: https://chahub-staging.herokuapp.com/. If not create one and ensure you can login
- Goto the Chagrade staging server at http://134.158.74.61/ and click `sign-in` (The wording of this will probably change, or the process will slightly). This should take you to the Chahub staging server asking you to sign-in. Once logged in it will ask for authorization:

![image](https://user-images.githubusercontent.com/28552312/47170176-4947ea80-d2ba-11e8-9f79-60d38f187343.png)

- After clicking authorize you should be taken back to Chagrade where it will ask you to set a password for this site. (We don't have Chahub send passwords)
- You should now be back at the index of Chagrade and should be able to login with your Chahub username, and the password you just set.

### Basic Class Creation:
- Once logged in, click `I'm an Instructor`. If this is your first time, it will ask for a university name.

![image](https://user-images.githubusercontent.com/28552312/47170405-cbd0aa00-d2ba-11e8-9e9a-4bf779c924e3.png)

- You should now be at the main class management page.

![image](https://user-images.githubusercontent.com/28552312/47170440-dee37a00-d2ba-11e8-8883-e9402688d584.png)

- Click create a class, and fill in the form with some basic details:

![image](https://user-images.githubusercontent.com/28552312/47170484-fcb0df00-d2ba-11e8-91fa-1272fc0037f8.png)

- You should now have a class in the table like so:

![image](https://user-images.githubusercontent.com/28552312/47170556-2964f680-d2bb-11e8-8bf0-4f3a780ebdd5.png)

- Clicking Edit should take you to the class wizard page. From here you can access the `steps` for the wizard, and edit the class details:

![image](https://user-images.githubusercontent.com/28552312/47170581-3eda2080-d2bb-11e8-9bb8-97dc5a7646af.png)

The only pages not templated so far are the grading homework pages and the form for creating homework. The reset should be templated out or almost finished but currently have no back-end functionality.

![screencapture-134-158-74-61-klasses-wizard-1-enroll-2018-10-18-09_51_44](https://user-images.githubusercontent.com/28552312/47170666-7ba61780-d2bb-11e8-81d9-c1d1c4508bc9.png)

![screencapture-134-158-74-61-klasses-wizard-1-define_homework-2018-10-18-09_51_52](https://user-images.githubusercontent.com/28552312/47170674-82348f00-d2bb-11e8-9071-ab7cb42adc4e.png)

![screencapture-134-158-74-61-klasses-wizard-1-activate_class-2018-10-18-09_51_58](https://user-images.githubusercontent.com/28552312/47170689-882a7000-d2bb-11e8-8422-a2d4b6e7037d.png)

**Comment by madclam** [comment]
Great job. Here are the issues found:
Home page: 
- make font contrast better 
- change icon color to blue
- point help to Wiki
Authentication:
- add password recovery
- change codalab logo to chahub logo
- redirect to chagrade
- share hash code of password (no need for multiple passwords)
- once authentication terms are accepted, we should not see that page ever again
Other pages:
- add cancel buttons on editor pages
