### ISSUE TITLE
Testing Instructions for Homework, Submissions, Activating Classes, Adding Students

### ISSUE THREAD

**Issue by Tthomas63** [codalab/chagrade#18]
Server IP and previous info can be found here: https://github.com/codalab/chagrade/issues/16

### Enroll Students (One By One for now):

- Sign into Chagrade, and create a new class if necessary from the instructor overview (Home->I'm an Instructor). Goto the enroll students page of the wizard. The page should look like this:
![image](https://user-images.githubusercontent.com/28552312/48238190-e3adc200-e37e-11e8-8a35-1c111d98608b.png)

- Clicking add user should give us this pop-up modal:
![image](https://user-images.githubusercontent.com/28552312/48238236-15bf2400-e37f-11e8-9d3b-83d66afbf4c5.png)

- If we enter a student's username and a student id and they are already authorized on Chagrade through Chahub, it will add them to the class. Same if we supply an email and an id. 
- However, if we supply all three fields and the student is not already authorized on Chagrade, it should create a blank account with that username/email combo waiting for them to login.

- You should add yourself to your class if you would like to test submitting homework and such later manually.

### Defining Homework:

- Next click go-to the define homework page. We should see the overview which looks like the following (Note: I do already have a class):
![image](https://user-images.githubusercontent.com/28552312/48238366-a4cc3c00-e37f-11e8-93ff-dbe0f189b7ca.png)

- Click on the `Create Homework` button to get to the form which looks like so:
![image](https://user-images.githubusercontent.com/28552312/48238435-de9d4280-e37f-11e8-8a49-3e495e400d94.png)

- From here you can fill in all the normal fields, and then for extra questions and defining the criteria you can press the related buttons. You should be able to add as many as you like (Un-tested):
![image](https://user-images.githubusercontent.com/28552312/48238546-3cca2580-e380-11e8-9a9e-adde27fd49ea.png)

- Pressing submit after you're done (and there are no errors) should bring you back to the homework definition overview.

- Pressing edit for the definition should bring you back to the same form but with some options to delete the extra criteria and questions. For now it is not possible to add criteria and questions from the edit page.
![image](https://user-images.githubusercontent.com/28552312/48238643-89adfc00-e380-11e8-90d8-1f854d8974df.png)

### Activating Classes:

- Goto the last step, the activate page. It should look like so for right now:
![image](https://user-images.githubusercontent.com/28552312/48238756-017c2680-e381-11e8-869c-f8b95e3fbb1b.png)

- You should be able to activate and de-activate the class from here without refreshing the page by clicking the button accordingly. There should be a confirmation and a success message in the upper right. 
![image](https://user-images.githubusercontent.com/28552312/48238807-2e303e00-e381-11e8-8334-71b086a9427a.png)

- Leave the class on activated for the next step.

### Submitting Homework:

- Click the home button to get back to the home page, then click `I'm a Student` to get to the student overview:
![image](https://user-images.githubusercontent.com/28552312/48238846-5750ce80-e381-11e8-8397-b565b31eb809.png)

- Right now there's not much information here, but the button (re-labeled later to 'View Homework') should bring us to the homework overview page for that class.
![image](https://user-images.githubusercontent.com/28552312/48238884-88310380-e381-11e8-9b4a-3c35c0bc80fd.png)

- This page does not have much information either yet, but clicking `View/Submit` homework should take us to the homework submission page, which has all the fields according to the definition.
![image](https://user-images.githubusercontent.com/28552312/48238935-bf9fb000-e381-11e8-8724-8e74e90ee6aa.png)

- After filling out the necessary details (If needed for submission url, just put the current url), click the submit button. We should be taken back to the class homework overview.

### Grading Homework:

- Head back over to the instructor side of Chagrade, and edit your class. Go-to the grade homework step. We should see something like this (Minus the grade):
![image](https://user-images.githubusercontent.com/28552312/48239050-3c328e80-e382-11e8-9fd7-8f9fececa417.png)

- Clicking edit should bring us to the grading form which looks like so with the criteria we had earlier and the student's answers:
![image](https://user-images.githubusercontent.com/28552312/48239097-756afe80-e382-11e8-9544-7db1b94972be.png)

- From here we can grade them based on the criteria and hit submit. We should be taken back to the grade submission over view page where we were before. The submission should now have a grade averaged from the criteria answers. (Total Points Scored / Total Points Possible )

**Comment by madclam** [comment]
This was tested and test results are logged in [meeting minutes](https://sites.google.com/a/chalearn.org/platform/meeting-minutes/chagrade).
Q1+2: ready to bill
Q3+4: only challenge submission missing + authentication cleanup
Q5: will include changes to minor issues and bug fixes.
