### ISSUE TITLE
V1.5 API

### ISSUE THREAD

**Issue by DWL3** [codalab/chagrade#20]

**Comment by Tthomas63** [comment]
- [x] Download submission from github repo
  - Downloaded as a temporary file
- [x] Upload to storage URL returned by v1.5 API
  - Should be a pretty universal solution. Unless Azure requires specific headers
- [x] Finalize Submission on phases for competition
  - Get phases for competition from v1.5 API
  - Post submission to all phases
- [x] Submission ID/Info stored on Chagrade (On models)
  - Store submission_id on Homework:Submission
  - Method for grabbing score from v1.5(?)
 - [x] View or API endpoint to add chagrade bot to competition
- [x] v1.5 API Endpoints to return submission info (Score)
