### ISSUE TITLE
Publishing Grades:

### ISSUE THREAD

**Issue by Tthomas63** [codalab/chagrade#27]
- Make it so grades are `publishable`. IE: If it does not have a flag `published`, don't show it.

**Comment by madclam** [comment]
Grade: Do not divide the grade by the total number of points.
Show it as a fraction e.g. 4 / 5
if the grade is 4 and the total number of points is 5

**Comment by madclam** [comment]
Challenge submissions do not seem to work.
Will the challenge score appear when you grade?
At the moment it does not.

**Comment by madclam** [comment]
The comments to the students are not visible to the students.

**Comment by madclam** [comment]
Download grade from http://chagrade.lri.fr/profiles/
instructor_overview/ does not work. Nor from
http://chagrade.lri.fr/klasses/wizard/6/grade_homework
