### ISSUE TITLE
Edit team: "Error fetching team: not found"

### ISSUE THREAD

**Issue by Didayolo** [codalab/chagrade#47]
Hi,

Firstly, congrats for Chagrade. It works pretty well and the interface is beautiful.

Here is a bug I found while testing it as instructor:

When trying to edit teams to add a new student in a team I got the following error:

`"Error fetching team: not found"`

And then the fields are empty.

**Comment by gibsonbailey** [comment]
Addressed this in commit [a7c3acf](https://github.com/codalab/chagrade/commit/a7c3acf37127c6bf5c6319bdc75a40ab4bccf634) on `github_social_auth` branch.
