### ISSUE TITLE
Grade homework: issue with links

### ISSUE THREAD

**Issue by Didayolo** [codalab/chagrade#48]
In the "grade homework" zone, I found out that the "link to challenge" URL referred to the main website URL ([codalab.lri.fr](url)) **instead of the challenge URL.** 

This occurs despite the fact that the challenge URL is well specified in the homework parameters.

![chagrade_issue](https://user-images.githubusercontent.com/11784999/64802687-8597cf80-d58b-11e9-9bd8-d76363364f5e.png)

Also, this is not an error but it could be improved: in "grade homework" there is **no link to the student's submission**. In student's view we have access to submissions (at least the score and a link to the zip file) but not in instructor's view. It means that we have to go through submissions in the challenge itself by hand and find which one is related to this homework.

**Comment by gibsonbailey** [comment]
Addressed in commit [0aa0202](https://github.com/codalab/chagrade/commit/0aa02025deba9252cad9b98c1aa2497bcd6aa737) on `github_social_auth` branch.
